childBlocks:
  - textContent
field: df60cedc-a0c3-43b1-8e6d-2a0d438dd151 # Page Builder
fieldLayouts:
  07221dec-b1e8-4229-b184-23236a9a8ee8:
    tabs:
      -
        elements:
          -
            fieldUid: 8d99434e-ca23-4a1d-ab99-a84fe4dbece6 # Span
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: contentBlock
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Content Block'
sortOrder: 6
topLevel: false
