columnSuffix: null
contentColumnType: string
fieldGroup: e3dba398-e51b-4b6c-b9d7-fb2f76388902 # Assets
handle: imageList
instructions: ''
name: 'Image List'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a85f2bb3-ff58-49a1-99a1-9e88cb12737f' # General
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a85f2bb3-ff58-49a1-99a1-9e88cb12737f' # General
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
