enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  d516bcb9-a47c-42b3-8003-0b9ae3cfdd69: # Vite Test
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
